workflows:
  android-workflow:
    name: Native Android
    max_build_duration: 60
    scripts:
      - name: Build debug apk
        script: ./gradlew assembleDebug
      - name: Build debug apk
        script: ls app/build/outputs/apk/debug/*.apk
    artifacts:
      - app/build/outputs/apk/debug/*.apk
    publishing:
      email:
        recipients:
          - daniel.zaczek@appwise.pl
